// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "dify-api-key": string;
      "dify-base-url": string;
      "dify-kb-id": string;
      "include-subcollections": boolean;
      "selected-collections": string;
      "auto-sync-interval": number;
      "last-sync-time": string;
    };
  }
}
